

services:
  # Symfony service
  symfony:
    image: php:8.2-fpm
    container_name: symfony
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    networks:
      - symfony_net
    depends_on:
      - postgres

  # PostgreSQL service
  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgresqlcode
      POSTGRES_DB: symfony_project
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - symfony_net

  # Nginx service
  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./public:/var/www/html/public
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    networks:
      - symfony_net
    depends_on:
      - symfony

volumes:
  postgres_data:

networks:
  symfony_net:
    driver: bridge
